import { Metadata } from 'next'

import './globals.css'
import Header from '@/components/header/Header'
import Menu from '@/components/menu/Menu'

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'PURPLESHOP'
	// description: 'Generated by create next app',
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<div className='flex h-full flex-col'>
					<Header />
					<main className='flex h-full flex-row'>
						<Menu />
						{children}
					</main>
				</div>
			</body>
		</html>
	)
}
